apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hmd4g8ac9-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hmd4g8ac9-go 
  name: hmd4g8ac9-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hmd4g8ac9-go 
